---
title: "Antarctcia Map"
output: pdf_document
---


```{r setup, include=FALSE}
#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", "ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata","rgeos"))
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggspatial")
library(ggrepel)
library(scales)
library(tidyverse)
library(stringr)
```

```{r setting work directory aka save}
#setwd("/Users/Chris Carnivale/OneDrive/Desktop/PhD_dissertation_data/Antarctica_station_map/")
setwd("/Users/christophercarnivale/Downloads/Antarctic_Map_files/")
```

## Thanks to JD for sharing his code on Github

All code can be found at: https://github.com/jeandavidgrattepanche/RandomScripts/blob/master/Map/Antarctica_map.R

```{r first attempt to pull map data }
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
#world_points<- st_centroid(world)
#world_points <- cbind(world, st_coordinates(st_centroid(world$geometry)))

#read in data file that houses stations sampled info
stations <- read.csv("/Users/Chris Carnivale/OneDrive/Desktop/PhD_dissertation_data/Antarctica_station_map/Station_locations.csv")


```

```{r extracting ggplot default color codes for 5 groups}
color_number <- 5
default_ggplot_hexcodes <- hue_pal()
show_col(hue_pal()(color_number))
#i've gotted the hex codes used for my personal graphs. I've added them into the color column of the csv file from jd.
#NOW to go and attempt to make the maps.
```


```{r making the first map}
ggplot(data = world) +
	geom_sf() +
#	geom_text(data= world_points,aes(x=X, y=Y, label=name),color = "darkblue", fontface = "bold", check_overlap = FALSE) +
	geom_point(data= stations, aes(x = longitude, y = latitude), size = 2, shape = 23, fill = stations$gcolor ) +
	geom_text(data= stations,aes(x= longitude - 0.3, y= latitude, label=ï..station),color = stations$gcolor,  check_overlap = FALSE) +	
	annotation_scale(location = "br", width_hint = 0.5) +
	annotation_north_arrow(location = "br", which_north = "true", pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), style = north_arrow_fancy_orienteering) +
	coord_sf(xlim = c(-70.5, -58.2), ylim = c(-68.9, -63.5), expand = FALSE)
	
# version 2 of the map... coastline at finer scale
library(mapdata)

world2 <- map("worldHires", fill = T, plot = F)
world2 <- st_as_sf(world2)
ggplot(data = world2) +
	geom_sf() +
#	geom_text(data= world_points,aes(x=X, y=Y, label=name),color = "darkblue", fontface = "bold", check_overlap = FALSE) +
	geom_point(data= stations, aes(x = longitude, y = latitude), size = 2, shape = 23, fill = stations$gcolor ) +
	geom_text(data= stations,aes(x= longitude - 0.3, y= latitude, label=ï..station),color = stations$gcolor,  check_overlap = FALSE, fontface = "bold") +	
	annotation_scale(location = "br", width_hint = 0.5) +
	annotation_north_arrow(location = "br", which_north = "true", pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), style = north_arrow_fancy_orienteering) +
	coord_sf(xlim = c(-70.5, -58.2), ylim = c(-68.9, -63.5), expand = FALSE)

#The customization is limited here since they are all on the same dataset. I need to filter out those that I need to customize specifically and then add them as their own annotations individually. Basically, build it from scratch.

#filter step here
straits <- c("Gerlache Strait", "Grandidier Channel")
seas <- c("Southern Ocean", "Weddel Sea")
Palm_marg <- c("Palmer Station", "Marguerite Bay")
stations_filtered <- stations[c(1,3,5:7,9:12),]
stations_for_annotations_straits <- stations[c(22,23),]
stations_for_annotations_Palm_marg <- stations[c(19,20),]
stations_for_annotations_seas <- stations[c(21,24),]
stations_sampled <- filter(stations, !gcolor == "grey50")
#build new plot
ggplot(data = world2) +
	geom_sf() +
#	geom_text(data= world_points,aes(x=X, y=Y, label=name),color = "darkblue", fontface = "bold", check_overlap = FALSE) +
	geom_point(data= stations_filtered, aes(x = longitude, y = latitude), size = 2, shape = 23, fill = stations_filtered$gcolor ) +
	geom_text(data= stations_filtered,aes(x= longitude - 0.3, y= latitude, label=ï..station),color = stations_filtered$gcolor,  check_overlap = FALSE, fontface = "bold") +	
	annotation_scale(location = "br", width_hint = 0.5) +
	annotation_north_arrow(location = "br", which_north = "true", pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), style = north_arrow_fancy_orienteering) +
	coord_sf(xlim = c(-70.5, -58.2), ylim = c(-68.9, -63.5), expand = FALSE)+
  annotate("text", x = stations_for_annotations_Palm_marg$longitude-0.55, y = stations_for_annotations_Palm_marg$latitude+0.05, label = str_wrap(Palm_marg, width = 5), color = "grey50", size = 3.5)+	geom_point(data= stations_for_annotations_Palm_marg[1,], aes(x = stations_for_annotations_Palm_marg[1,3], y = stations_for_annotations_Palm_marg[1,2]), size = 2, shape = 23, fill = stations_for_annotations_Palm_marg[1,5])+
  annotate("text", x = stations_for_annotations_seas$longitude+0.2, y = stations_for_annotations_seas$latitude-0.5, label = seas, size = 8, color = "grey50", fontface = "bold")+
  annotate("text", x = stations_for_annotations_straits[1,3]+0.9, y = stations_for_annotations_straits[1,2]+0.5, label = "Gerlache Strait", angle = 45, color = "grey50")+
  annotate("text", x = stations_for_annotations_straits[2,3], y = stations_for_annotations_straits[2,2]-0.35, label = "Grandidier Channel", angle = 45, color = "grey50")+xlab("Longitude")+ylab("Latitude")

#looks like I need to add each strait individually which I will now do above after I try adding the other
#This plot only has the stations used in the analysis...I will make a second map that will contain all of the stations which we sampled next....basically copy and paste after all the work with the annotation is done.

#plot with all the stations sampled
ggplot(data = world2) +
	geom_sf() +
#	geom_text(data= world_points,aes(x=X, y=Y, label=name),color = "darkblue", fontface = "bold", check_overlap = FALSE) +
	geom_point(data= stations_sampled, aes(x = longitude, y = latitude), size = 2, shape = 23, fill = stations_sampled$gcolor ) +
	geom_text(data= stations_sampled,aes(x= longitude - 0.3, y= latitude, label=ï..station),color = stations_sampled$gcolor,  check_overlap = FALSE, fontface = "bold") +	
	annotation_scale(location = "br", width_hint = 0.5) +
	annotation_north_arrow(location = "br", which_north = "true", pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), style = north_arrow_fancy_orienteering) +
	coord_sf(xlim = c(-70.5, -58.2), ylim = c(-68.9, -63.5), expand = FALSE)+
  annotate("text", x = stations_for_annotations_Palm_marg$longitude-0.55, y = stations_for_annotations_Palm_marg$latitude+0.05, label = str_wrap(Palm_marg, width = 5), color = "grey50", size = 3.5)+	geom_point(data= stations_for_annotations_Palm_marg[1,], aes(x = stations_for_annotations_Palm_marg[1,3], y = stations_for_annotations_Palm_marg[1,2]), size = 2, shape = 23, fill = stations_for_annotations_Palm_marg[1,5])+
  annotate("text", x = stations_for_annotations_seas$longitude+0.2, y = stations_for_annotations_seas$latitude-0.5, label = seas, size = 8, color = "grey50", fontface = "bold")+
  annotate("text", x = stations_for_annotations_straits[1,3]+0.9, y = stations_for_annotations_straits[1,2]+0.5, label = "Gerlache Strait", angle = 45, color = "grey50")+
  annotate("text", x = stations_for_annotations_straits[2,3], y = stations_for_annotations_straits[2,2]-0.35, label = "Grandidier Channel", angle = 45, color = "grey50")+xlab("Longitude")+ylab("Latitude")

```

```{r saving the nice plot}
stations_filtered_plot <- ggplot(data = world2) +
	geom_sf() +
#	geom_text(data= world_points,aes(x=X, y=Y, label=name),color = "darkblue", fontface = "bold", check_overlap = FALSE) +
	geom_point(data= stations_filtered, aes(x = longitude, y = latitude), size = 2, shape = 23, fill = stations_filtered$gcolor ) +
	geom_text(data= stations_filtered,aes(x= longitude - 0.3, y= latitude, label=ï..station),color = stations_filtered$gcolor,  check_overlap = FALSE, fontface = "bold") +	
	annotation_scale(location = "br", width_hint = 0.5) +
	annotation_north_arrow(location = "br", which_north = "true", pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"), style = north_arrow_fancy_orienteering) +
	coord_sf(xlim = c(-70.5, -58.2), ylim = c(-68.9, -63.5), expand = FALSE)+
  annotate("text", x = stations_for_annotations_Palm_marg$longitude-0.55, y = stations_for_annotations_Palm_marg$latitude+0.05, label = str_wrap(Palm_marg, width = 5), color = "grey50", size = 3.5)+	geom_point(data= stations_for_annotations_Palm_marg[1,], aes(x = stations_for_annotations_Palm_marg[1,3], y = stations_for_annotations_Palm_marg[1,2]), size = 2, shape = 23, fill = stations_for_annotations_Palm_marg[1,5])+
  annotate("text", x = stations_for_annotations_seas$longitude+0.2, y = stations_for_annotations_seas$latitude-0.5, label = seas, size = 8, color = "grey50", fontface = "bold")+
  annotate("text", x = stations_for_annotations_straits[1,3]+0.9, y = stations_for_annotations_straits[1,2]+0.5, label = "Gerlache Strait", angle = 45, color = "grey50")+
  annotate("text", x = stations_for_annotations_straits[2,3], y = stations_for_annotations_straits[2,2]-0.35, label = "Grandidier Channel", angle = 45, color = "grey50")+xlab("Longitude")+ylab("Latitude")

ggsave("antarctica_map.png",stations_filtered_plot, "png")
```



